/// Generated by AssetsRefGenerator on 2020/03/28
class Res {
  static const String  fina= "assets/final.png";
  static const String flag = "assets/flag.jpg";
  static const String goal = "assets/goal.jpg";
  static const String goa = "assets/goal.png";
  static const String goalfballrem = "assets/goalfballrem.png";
  static const String goalrem = "assets/goalrem.png";
  static const String gold = "assets/gold.png";
  static const String golfball = "assets/golfball.jpeg";
  static const String google = "assets/google.png";
  static const String log = "assets/log.jpeg";
  static const String logo1 = "assets/logo1.jpeg";
  static const String marker = "assets/marker.png";
  static const String one = "assets/one.png";
  static const String targetrem = "assets/targetrem.png";
}
